build:
  pythonVersion: 3.10

services:
  - type: worker
    name: discord-bot
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_TOKEN
        scope: run

  - type: web
    name: bot-webpage
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python web.py"
