build:
  pythonVersion: 3.10

services:
  - type: worker
    name: bot-zeus
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        scope: run
