build:
  pythonVersion: 3.10

services:
  - type: worker
    name: discord-bot
    runtime: python
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"

  - type: web
    name: bot-webpage
    runtime: python
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python web.py"
